name: Py-Script-on-Workflow

on:
    workflow_dispatch
#   push:
#     branches:
#       - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt

      - name: Execute Python Script
        id: run_script
        run: |
        
          python3 v4.py ip2.csv
        continue-on-error: true

      - name: Check Python Execution Result
        id: check_result
        run: |
          if [ "${{ steps.run_script.outcome }}" == "success" ]; then
            echo "Python execution successful"
          else
            echo "Python execution failed"
            exit 1
          fi

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tasks dependent on Job 1 success
        run: |
          echo "Job 1 succeeded, running Job 2 tasks."
          # Add the tasks to be run when Job 1 succeeds
