name: Py-Script-on-Workflow-v2

on:
    workflow_dispatch
#   push:
#     branches:
#       - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs: 
        script_execution_result: ${{ steps.check_result.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Execute Python Script
        id: run_script
        run: |
          python3 v4.py ip2.csv
        continue-on-error: true

      - name: Check Python Execution Result
        id: check_result
        run: |
          if [ "${{ steps.run_script.outcome }}" == "success" ]; then
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "result=failure" >> $GITHUB_OUTPUT
        # outputs:
        #   result: ${{ env.result }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.script_execution_result }} == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Python Execution Result
        id: check_result
        run: |
          if [ "${{ needs.job1.outputs.script_execution_result }}" == "success" ]; then
            echo "Python execution successful"
          else
            echo "Python execution failed"
          fi
